# -*- coding: utf-8 -*-
"""Feature_Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1temi0T99PxQoZeR3yaY0hTr98TuLU_xs
"""


import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import chi2_contingency, pointbiserialr, mannwhitneyu
import warnings
warnings.filterwarnings("ignore")

# Plot style
sns.set_theme(style="whitegrid", palette="husl")
plt.rcParams.update({"figure.dpi": 120, "figure.figsize": (12, 5)})


# Load raw data from data_source/raw using a path relative to this script
script_dir = os.path.dirname(os.path.abspath(__file__))
raw_path = os.path.abspath(os.path.join(script_dir, '../../data_source/raw/manufacturing.csv'))
df = pd.read_csv(raw_path)
if "Unnamed: 0" in df.columns:
    df.drop(columns=["Unnamed: 0"], inplace=True)

# Binary anomaly flag (1 = any breakdown, 0 = none)
df["BREAKDOWN"] = (df["BREAKS"] > 0).astype(int)

print(f"Dataset shape : {df.shape}")
print(f"\nBREAKS distribution:\n{df['BREAKS'].value_counts().sort_index()}")
print(f"\nBreakdown rate: {df['BREAKDOWN'].mean()*100:.1f}%")

df.drop_duplicates()
df.duplicated().sum()
df.isna().sum()

df.head()

df.describe()

df['Anomaly_identification'] = (df['BREAKS'] > 0).astype(int)
print(f"Updated BREAKS distribution:\n{df['BREAKS'].value_counts().sort_index()}")

df.head()

df["S1_efficiency"]    = df["Processing_Time_S1"] / (df["Finish_time_S1"] - df["Start_time_S1"] + 1)
df["S2_efficiency"]    = df["Processing_Time_S2"] / (df["Finish_Time_S2"] - df["Start_time_S2"] + 1)
df["S3_efficiency"]    = df["Processing_Time_S3"] / (df["Finish_time_S3"] - df["Start_time_S3"] + 1)
df["S4_efficiency"]    = df["Processing_Time_S4"] / (df["Finish_time"] - df["Start_time_s4"] + 1)

df["wait_to_process_ratio"] = df["Overall_waiting_time"] / (df["Overall_processing_time"] + 1)
df["longest_stage"]         = df[["Processing_Time_S1","Processing_Time_S2",
                                   "Processing_Time_S3","Processing_Time_S4"]].max(axis=1)
df["shortest_stage"]        = df[["Processing_Time_S1","Processing_Time_S2",
                                   "Processing_Time_S3","Processing_Time_S4"]].min(axis=1)
df["stage_time_std"]        = df[["Processing_Time_S1","Processing_Time_S2",
                                   "Processing_Time_S3","Processing_Time_S4"]].std(axis=1)
df["stage_time_range"]      = df["longest_stage"] - df["shortest_stage"]
df["is_tardy"]              = (df["Tardiness"] > 0).astype(int)
df["tardiness_per_unit"]    = df["Tardiness"] / (df["Overall_processing_time"] + 1)

z_features = ["Overall_waiting_time", "Overall_processing_time", "Tardiness",
               "Processing_Time_S1","Processing_Time_S2","Processing_Time_S3","Processing_Time_S4"]
for col in z_features:
    df[f"zscore_{col}"] = np.abs(stats.zscore(df[col]))
    df[f"flag_z_{col}"] = (df[f"zscore_{col}"] > 3).astype(int)

df["total_z_flags"] = df[[f"flag_z_{c}" for c in z_features]].sum(axis=1)

print("\n=== ENGINEERED FEATURES — Sample ===")
eng_feats = ["S1_efficiency","S2_efficiency","S3_efficiency","S4_efficiency",
             "wait_to_process_ratio","stage_time_std","stage_time_range",
             "is_tardy","tardiness_per_unit","total_z_flags"]
print(df[eng_feats].describe().round(3).to_string())

print("\n=== ENGINEERED FEATURES → BREAKDOWN CORRELATION ===")
for col in eng_feats:
    r, p = pointbiserialr(df["BREAKDOWN"], df[col].replace([np.inf, -np.inf], np.nan).fillna(0))
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
    print(f"  {col:<30}: r={r:+.4f}  p={p:.4e}  {sig}")

print("\n=== STEP 7 — STATISTICAL ANOMALY FLAGS ===")

key_feats = ["Overall_waiting_time", "Overall_processing_time", "Tardiness",
             "wait_to_process_ratio", "stage_time_std"]

# Z-Score method (|z| > 3)
z_scores = np.abs(stats.zscore(df[key_feats].fillna(0)))
z_anomaly = (z_scores > 3).any(axis=1).astype(int)

# IQR method
def iqr_flag(series):
    q1, q3 = series.quantile(0.25), series.quantile(0.75)
    iqr = q3 - q1
    return ((series < q1 - 1.5*iqr) | (series > q3 + 1.5*iqr)).astype(int)

iqr_flags = df[key_feats].apply(iqr_flag)
iqr_anomaly = iqr_flags.any(axis=1).astype(int)

print(f"Z-Score anomalies detected : {z_anomaly.sum():,} ({z_anomaly.mean()*100:.1f}%)")
print(f"IQR     anomalies detected : {iqr_anomaly.sum():,} ({iqr_anomaly.mean()*100:.1f}%)")
print(f"\nZ-Score vs BREAKDOWN:\n{pd.crosstab(z_anomaly, df['BREAKDOWN'], rownames=['Z-flag'], colnames=['BREAKDOWN'])}")

print(f"\nIQR vs BREAKDOWN:\n{pd.crosstab(iqr_anomaly, df['BREAKDOWN'], rownames=['IQR-flag'], colnames=['BREAKDOWN'])}")

# Save processed DataFrame to data_source/Processed using a path relative to this script
processed_path = os.path.abspath(os.path.join(script_dir, '../../data_source/Processed/processed_manufacturing.csv'))
df.to_csv(processed_path, index=False)
print(f"Processed data saved to {processed_path}")