# -*- coding: utf-8 -*-
"""Data_Preprocessing_Anlaysis_Anomaly_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDHsSZmLr_4pfXUItueCOqcRU2P9uOmx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import chi2_contingency, pointbiserialr, mannwhitneyu
import warnings
warnings.filterwarnings("ignore")

# Plot style
sns.set_theme(style="whitegrid", palette="husl")
plt.rcParams.update({"figure.dpi": 120, "figure.figsize": (12, 5)})

# Load
df = pd.read_csv("manufacturing.csv")
df.drop(columns=["Unnamed: 0"], inplace=True)

# Binary anomaly flag (1 = any breakdown, 0 = none)
df["BREAKDOWN"] = (df["BREAKS"] > 0).astype(int)

print(f"Dataset shape : {df.shape}")
print(f"\nBREAKS distribution:\n{df['BREAKS'].value_counts().sort_index()}")
print(f"\nBreakdown rate: {df['BREAKDOWN'].mean()*100:.1f}%")

df.duplicated().sum()

df.isna().sum()

df[df.duplicated()]

df[df['ID']==12]

df.drop_duplicates(inplace=True)
print(f"DataFrame shape after removing duplicates: {df.shape}")

# ─────────────────────────────────────────────────────────────
# STEP 1 — STATISTICAL SUMMARY
# ─────────────────────────────────────────────────────────────
numeric_cols = [
    "Priority", "Family_type",
    "Processing_Time_S1", "Processing_Time_S2",
    "Processing_Time_S3", "Processing_Time_S4",
    "Overall_processing_time", "Overall_waiting_time", "Tardiness"
]

print("\n=== DESCRIPTIVE STATISTICS ===")
desc = df[numeric_cols].describe().T
desc["skewness"] = df[numeric_cols].skew()
desc["kurtosis"] = df[numeric_cols].kurt()
desc["IQR"]      = df[numeric_cols].quantile(0.75) - df[numeric_cols].quantile(0.25)
desc["CV%"]      = (df[numeric_cols].std() / df[numeric_cols].mean() * 100).round(1)
print(desc.round(2).to_string())

# Shapiro-Wilk normality test (on a sample — test is slow on N>5000)
print("\n=== NORMALITY (Shapiro-Wilk, n=500 sample) ===")
sample = df[numeric_cols].sample(500, random_state=42)
for col in numeric_cols:
    stat, p = stats.shapiro(sample[col].dropna())
    print(f"  {col:<30} W={stat:.4f}  p={p:.4e}  {'NORMAL' if p>0.05 else 'NOT normal'}")

# ─────────────────────────────────────────────────────────────
# STEP 2 — UNIVARIATE ANALYSIS
# ─────────────────────────────────────────────────────────────

# 2a — Distribution of BREAKS (target)
fig, axes = plt.subplots(1, 2, figsize=(13, 4))
df["BREAKS"].value_counts().sort_index().plot(
    kind="bar", ax=axes[0], color=["#2ecc71","#e74c3c","#c0392b","#922b21"], edgecolor="black"
)
axes[0].set_title("BREAKS Value Counts (Target Variable)")
axes[0].set_xlabel("Number of Breakdowns"); axes[0].set_ylabel("Count")
for p in axes[0].patches:
    axes[0].annotate(f"{int(p.get_height()):,}", (p.get_x()+0.05, p.get_height()+50))

axes[1].pie(
    df["BREAKS"].value_counts().sort_index(),
    labels=["0 breaks","1 break","2 breaks","3 breaks"],
    autopct="%1.1f%%", startangle=90,
    colors=["#2ecc71","#e67e22","#e74c3c","#922b21"]
)
axes[1].set_title("BREAKS Proportion")
plt.suptitle("Target Variable Distribution", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("01_target_distribution.png", bbox_inches="tight")
plt.show()
print("→ Saved: 01_target_distribution.png")

# 2b — Numeric feature distributions
fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()
for i, col in enumerate(numeric_cols):
    axes[i].hist(df[col], bins=40, color="#3498db", edgecolor="white", alpha=0.8)
    axes[i].axvline(df[col].mean(),   color="red",    linestyle="--", label="Mean")
    axes[i].axvline(df[col].median(), color="orange", linestyle=":",  label="Median")
    axes[i].set_title(f"{col}\nskew={df[col].skew():.2f}")
    axes[i].legend(fontsize=7)
plt.suptitle("Step 2b — Numeric Feature Distributions", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("02_univariate_distributions.png", bbox_inches="tight")
plt.show()
print("→ Saved: 02_univariate_distributions.png")

# 2c — Categorical columns
cat_cols = ["First_stage", "Second_stage", "Third_stage", "Fourth_stage"]
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
for i, col in enumerate(cat_cols):
    vc = df[col].value_counts()
    vc.plot(kind="bar", ax=axes[i], color="#9b59b6", edgecolor="black")
    axes[i].set_title(col); axes[i].set_xlabel(""); axes[i].tick_params(rotation=30)
plt.suptitle("Step 2c — Categorical Feature Frequencies", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("03_categorical_distributions.png", bbox_inches="tight")
plt.show()
print("→ Saved: 03_categorical_distributions.png")

# 2d — Box plots & outlier detection via IQR
print("\n=== IQR OUTLIER COUNT PER FEATURE ===")
fig, axes = plt.subplots(1, len(numeric_cols), figsize=(22, 5))
for i, col in enumerate(numeric_cols):
    q1, q3 = df[col].quantile(0.25), df[col].quantile(0.75)
    iqr = q3 - q1
    lo, hi = q1 - 1.5*iqr, q3 + 1.5*iqr
    n_out = ((df[col] < lo) | (df[col] > hi)).sum()
    print(f"  {col:<30}: {n_out:5d} outliers ({n_out/len(df)*100:.1f}%)")
    axes[i].boxplot(df[col].dropna(), patch_artist=True,
                    boxprops=dict(facecolor="#3498db", alpha=0.6))
    axes[i].set_title(col, fontsize=8); axes[i].set_xlabel("")
plt.suptitle("Step 2d — Box Plots (IQR Outlier Visualization)", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("04_boxplots.png", bbox_inches="tight")
plt.show()
print("→ Saved: 04_boxplots.png")

"""Based on the p-values:

Highly Significant Differences (p < 0.001 - marked with ***): Priority, Processing_Time_S1, Processing_Time_S2, Processing_Time_S3, Processing_Time_S4, Overall_processing_time, and Tardiness all show a very strong statistical difference between the 'no breakdown' and 'breakdown' groups. This suggests these factors are highly correlated with the occurrence of breakdowns.

No Significant Difference (p > 0.05 - marked with ns): Family_type and Overall_waiting_time do not show a statistically significant difference between the two groups. This means that, based on this test, these features are unlikely to be strong predictors of breakdowns.

In summary, most of the processing time metrics, priority, and tardiness are strongly associated with breakdowns, while family type and overall waiting time are not.

"""

# 3a — Numeric features vs BREAKDOWN (Mann-Whitney U test)
print("\n=== NUMERIC vs BREAKDOWN — Mann-Whitney U Test ===")
normal   = df[df["BREAKDOWN"] == 0]
anomaly  = df[df["BREAKDOWN"] == 1]

fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()
for i, col in enumerate(numeric_cols):
    u_stat, p_val = mannwhitneyu(normal[col], anomaly[col], alternative="two-sided")
    sig = "***" if p_val < 0.001 else ("**" if p_val < 0.01 else ("*" if p_val < 0.05 else "ns"))
    print(f"  {col:<30} U={u_stat:.0f}  p={p_val:.4e}  {sig}")

    axes[i].hist(normal[col],  bins=40, alpha=0.6, label="No Breakdown", color="#2ecc71", density=True)
    axes[i].hist(anomaly[col], bins=40, alpha=0.6, label="Breakdown",    color="#e74c3c", density=True)
    axes[i].set_title(f"{col}\np={p_val:.2e} {sig}", fontsize=9)
    axes[i].legend(fontsize=7)
plt.suptitle("Step 3a — Feature Distributions: Normal vs Breakdown", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("05_bivariate_numeric.png", bbox_inches="tight")
plt.show()
print("→ Saved: 05_bivariate_numeric.png")

# 3d — Point-Biserial Correlation (numeric vs binary BREAKDOWN)
print("\n=== POINT-BISERIAL CORRELATION (numeric vs BREAKDOWN) ===")
correlations = {}
for col in numeric_cols:
    r, p = pointbiserialr(df["BREAKDOWN"], df[col])
    correlations[col] = {"r": r, "p": p}
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
    print(f"  {col:<30}: r={r:+.4f}  p={p:.4e}  {sig}")

corr_df = pd.DataFrame(correlations).T.sort_values("r", ascending=False)
fig, ax = plt.subplots(figsize=(10, 5))
colors = ["#e74c3c" if r > 0 else "#3498db" for r in corr_df["r"]]
corr_df["r"].plot(kind="barh", ax=ax, color=colors, edgecolor="black")
ax.axvline(0, color="black", linewidth=0.8)
ax.set_title("Step 3d — Point-Biserial Correlation with BREAKDOWN", fontsize=12, fontweight="bold")
ax.set_xlabel("Correlation (r)")
plt.tight_layout(); plt.savefig("08_point_biserial.png", bbox_inches="tight")
plt.show()
print("→ Saved: 08_point_biserial.png")

# 3e — Correlation Heatmap (numeric features)
fig, ax = plt.subplots(figsize=(12, 9))
corr_matrix = df[numeric_cols + ["BREAKS", "BREAKDOWN"]].corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt=".2f", cmap="coolwarm",
            center=0, ax=ax, linewidths=0.5, cbar_kws={"shrink": 0.8})
ax.set_title("Step 3e — Feature Correlation Heatmap", fontsize=13, fontweight="bold")
plt.tight_layout(); plt.savefig("09_correlation_heatmap.png", bbox_inches="tight")
plt.show()
print("→ Saved: 09_correlation_heatmap.png")

